### ISSUE TITLE
Improvement: Add possibly to run the server in background

### ISSUE THREAD

**Issue by benciks** [timewarrior-synchronize/timew-sync-server#68]
It would be nice if server could be ran in background and additional commands to stop the server and check logs would exist. This would help when deploying this on a server. Your option to run it in docker would be fine in this case, however, getting the keys in and out of docker container, is pretty complicated.

**Comment by joachimschmidt557** [comment]
On Linux, we recommend running `timew-sync-server` as a systemd (or other service manager) service. This is in our eyes the most straightforward way and will provide the correct amount of service supervision, which would otherwise have to be implemented tediously through pidfiles and other methods. I will add an example systemd service file to the repository.

Regarding the management of keys, we are aware of this issue. It is planned to move key management to the main database (currently SQLite), which simplifies a lot of the processing and maintenance of a `timew-sync-server` instance.

**Comment by vstollen** [comment]
I'll close this issue for now. If you have any additional questions, don't hesitate to ask.
